name: "SQLite HA DB Usage"
version: "1.0.15"
slug: "db-usage"
description: "Inspect Home Assistant recorder database usage. Only for SQLite databases."
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "manual"
init: false

panel_icon: mdi:database-eye
url: https://github.com/rpeyron/ha-dbusage

ports:
  "3000/tcp": 8042
ports_description:
  "3000/tcp": "Web UI for App"
ingress: true
ingress_port: 3000

host_db: true
map:
  - type: homeassistant_config
    path: /config
scheme: "http"
webui: "http://[HOST]:[PORT:3000]/"
options:
  log_level: "info"
schema:
  log_level: "list(trace|debug|info|warn|error)"